# Generated by Django 2.2 on 2020-05-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500)),
                ('registration_name', models.IntegerField(null=True)),
                ('mobile_number', models.IntegerField(null=True)),
                ('id_card', models.ImageField(upload_to='media')),
                ('registration_type', models.CharField(max_length=100)),
                ('number_of_tickets', models.IntegerField(default=1)),
            ],
        ),
    ]
