# Generated by Django 2.2 on 2020-05-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20200514_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_type',
            field=models.CharField(choices=[('self', 'self'), ('group', 'group'), ('corporate', 'corporate'), ('others', 'others')], max_length=100),
        ),
    ]
