# Generated by Django 2.1 on 2020-05-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20200519_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='mobile_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
